#--------------------------------------------------------------------------
# Set Target up
#--------------------------------------------------------------------------
set(TARGET_NAME cpp_app)
					
add_executable(${TARGET_NAME})

#--------------------------------------------------------------------------
# Sources
#--------------------------------------------------------------------------
list(APPEND app_SOURCES  #sources
						sfml/cppapp.cpp)

target_sources(${TARGET_NAME} PRIVATE ${app_SOURCES})

#--------------------------------------------------------------------------
# Add libraries
#--------------------------------------------------------------------------
# OWN
#--------------------------------------------------------------------------
list(APPEND sfml_LIB_SOURCES sfml_libs)

target_link_libraries(${TARGET_NAME} PUBLIC ${sfml_LIB_SOURCES})

#--------------------------------------------------------------------------
# EXTERNAL
#--------------------------------------------------------------------------

#--------------------------------------------------------------------------
# Include Directories
#--------------------------------------------------------------------------
#target_include_directories(${TARGET_NAME} PUBLIC
#							"${PROJECT_BINARY_DIR}"
#							)

#--------------------------------------------------------------------------
# Install
#--------------------------------------------------------------------------
install(TARGETS ${TARGET_NAME}
		DESTINATION ${INSTALL_BINDIR}
)